### ISSUE TITLE
群里发了 2.2.0- alpha，那代码在哪

### ISSUE THREAD

**Issue by orzyyyy** [DogReactor/AigisPlayer#71]

**Comment by Yukimir** [comment]
2.2.0-alpha不是我发的
是毁佬发的，我本来发给他测试的

**Comment by Yukimir** [comment]
你要看代码的话，代码在我自己fork的仓库里

**Comment by orzyyyy** [comment]
有地址吗，没 deb 爬不了塔就很急。

**Comment by Yukimir** [comment]
我在主仓库发布beta版了

只捱宅 <notifications@github.com> 于 2019年12月11日周三 08:48写道：
