### ISSUE TITLE
最小化窗口问题

### ISSUE THREAD

**Issue by eli5168** [DogReactor/AigisPlayer#84]
问个问题, 是怎么样实现最小化窗口还能保持游戏运行的?

因为我用chrome内核玩千年, gbf或者火车的时候, 只要不focus窗口chrome就会自动冻结窗口.

但我用AigisPlayer玩千年挂机大讨伐，最小化游戏不会有这个问题.

本身不是很了解网页代码所以比较好奇 >_<

谢谢.

**Comment by DeltAlice** [comment]
现代浏览器会提供一些机制来暂停一些程序在后台运行以节省资源，程序也可以主动这么做。见[https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#policies_in_place_to_aid_background_page_performance](Page Visibility API)
可以主动设置一些参数来关掉这些行为，electron里可能默认有一些别的设置（
